CONNECTION_STRING = "mongodb+srv://moorepj:RL05NFeWyexis43T@agsrmt.6jcivn0.mongodb.net/?retryWrites=true&w=majority"

LOST_ARK_SERVER_DROPDOWN_OPTIONS = [
    {'label': 'Adrinne', 'value': 'Adrinne'},
    {'label': 'Agaton', 'value': 'Agaton'},
    {'label': 'Akkan', 'value': 'Akkan'},
    {'label': 'Aldebaran', 'value': 'Aldebaran'},
    {'label': 'Antares', 'value': 'Antares'},
    {'label': 'Arcturus', 'value': 'Arcturus'},
    {'label': 'Asta', 'value': 'Asta'},
    {'label': 'Avesta', 'value': 'Avesta'},
    {'label': 'Azena', 'value': 'Azena'},
    {'label': 'Bergstrom', 'value': 'Bergstrom'},
    {'label': 'Calvasus', 'value': 'Calvasus'},
    {'label': 'Danube', 'value': 'Danube'},
    {'label': 'Elzowin', 'value': 'Elzowin'},
    {'label': 'Enviska', 'value': 'Enviska'},
    {'label': 'Evergrace', 'value': 'Evergrace'},
    {'label': 'Ezrebet', 'value': 'Ezrebet'},
    {'label': 'Galatur', 'value': 'Galatur'},
    {'label': 'Gienah', 'value': 'Gienah'},
    {'label': 'Kadan', 'value': 'Kadan'},
    {'label': 'Karta', 'value': 'Karta'},
    {'label': 'Kazeros', 'value': 'Kazeros'},
    {'label': 'Kharmine', 'value': 'Kharmine'},
    {'label': 'Lazenith', 'value': 'Lazenith'},
    {'label': 'Mari', 'value': 'Mari'},
    {'label': 'Mokoko', 'value': 'Mokoko'},
    {'label': 'Moonkeep', 'value': 'Moonkeep'},
    {'label': 'Neria', 'value': 'Neria'},
    {'label': 'Regulus', 'value': 'Regulus'},
    {'label': 'Rethramis', 'value': 'Rethramis'},
    {'label': 'Rohendel', 'value': 'Rohendel'},
    {'label': 'Sasha', 'value': 'Sasha'},
    {'label': 'Shandi', 'value': 'Shandi'},
    {'label': 'Slen', 'value': 'Slen'},
    {'label': 'Stonehearth', 'value': 'Stonehearth'},
    {'label': 'Thirain', 'value': 'Thirain'},
    {'label': 'Tortoyk', 'value': 'Tortoyk'},
    {'label': 'Trixion', 'value': 'Trixion'},
    {'label': 'Una', 'value': 'Una'},
    {'label': 'Valtan', 'value': 'Valtan'},
    {'label': 'Vern', 'value': 'Vern'},
    {'label': 'Vykas', 'value': 'Vykas'},
    {'label': 'Wei', 'value': 'Wei'},
    {'label': 'Zinnervale', 'value': 'Zinnervale'},
    {'label': 'Zosma', 'value': 'Zosma'}
]

NEW_WORLD_SERVER_DROPDOWN_OPTIONS = [
    {'label': 'Aaru', 'value': 'Aaru'},
    {'label': 'Abaton', 'value': 'Abaton'},
    {'label': 'Amarah', 'value': 'Amarah'},
    {'label': 'Artemis', 'value': 'Artemis'},
    {'label': 'Artorius', 'value': 'Artorius'},
    {'label': 'Asgard', 'value': 'Asgard'},
    {'label': 'Barri', 'value': 'Barri'},
    {'label': 'Castle of Steel', 'value': 'Castle of Steel'},
    {'label': 'Cleopatra', 'value': 'Cleopatra'},
    {'label': 'Crassus', 'value': 'Crassus'},
    {'label': 'Delos', 'value': 'Delos'},
    {'label': 'Devaloka', 'value': 'Devaloka'},
    {'label': 'El Dorado', 'value': 'El Dorado'},
    {'label': 'Gaea', 'value': 'Gaea'},
    {'label': 'Isabella', 'value': 'Isabella'},
    {'label': 'Kronos', 'value': 'Kronos'},
    {'label': 'Lilith', 'value': 'Lilith'},
    {'label': 'Maramma', 'value': 'Maramma'},
    {'label': 'Nysa', 'value': 'Nysa'},
    {'label': 'Nyx', 'value': 'Nyx'},
    {'label': 'Orofena', 'value': 'Orofena'},
    {'label': 'Seer', 'value': 'Seer'},
    {'label': 'Sutekh', 'value': 'Sutekh'},
    {'label': 'Valhalla', 'value': 'Valhalla'}
]

NEW_WORLD_SERVER_LIST = [
    "Aaru-EU Central",
    "Abaton-EU Central",
    "Amarah-US East",
    "Artemis-EU Central",
    "Artorius-SA East",
    "Asgard-EU Central",
    "Barri-EU Central",
    "Castle of Steel-US East",
    "Cleopatra-EU Central",
    "Crassus-EU Central",
    "Delos-AP Southeast",
    "Devaloka-SA East",
    "El Dorado-US West",
    "Gaea-SA East",
    "Isabella-US West",
    "Kronos-EU Central",
    "Lilith-US East",
    "Maramma-US East",
    "Nysa-EU Central",
    "Nyx-EU Central",
    "Orofena-US East",
    "Seer-US East",
    "Sutekh-AP Southeast",
    "Valhalla-US East"
]

LOST_ARK_SERVER_LIST = [
    "Adrinne-US East",
    "Akkan-US West",
    "Aldebaran-US East",
    "Antares-EU Central",
    "Armen-EU Central",
    "Arthetine-South America",
    "Asta-EU Central",
    "Avesta-US East",
    "Azena-US East",
    "Bergstrom-US West",
    "Blackfang-South America",
    "Calvasus-EU Central",
    "Danube-US East",
    "Ealyn-EU West",
    "Elzowin-US East",
    "Enviska-US West",
    "Evergrace-EU Central",
    "Ezrebet-EU Central",
    "Galatur-US East",
    "Kadan-EU Central",
    "Karta-US East",
    "Kazeros-South America",
    "Kharmine-US East",
    "Ladon-US East",
    "Lazenith-EU Central",
    "Mari-US West",
    "Mokoko-EU Central",
    "Neria-EU Central",
    "Nia-EU West",
    "Regulus-US East",
    "Rohendel-US West",
    "Sasha-US East",
    "Shandi-US West",
    "Slen-EU Central",
    "Thirain-EU Central",
    "Trixion-EU Central",
    "Una-US East",
    "Valtan-US West",
    "Vykas-US East",
    "Wei-EU Central",
    "Zinnervale-EU Central",
    "Zosma-US East"
]